### PR TITLE
U/stalderriel/ptc

### PR DESCRIPTION
**Pull request by bstalder**
this is mostly broken, give it a try!

### CODE REVIEW

**Comment by bechtol** [comment]
Multiple unrelated files to this pull request have been changed: Firefly.ipynb, matching.ipynb,  postage_stamp.ipynb, wcs_check.ipynb. Please remove these changes.

**Comment by bstalder** [comment]
btw, will need to add eotest from lsst-dm and "set up" in .user_setups.

**Comment by bechtol** [comment]
- This notebook would benefit from a quick description of the goals at the top
- Would also be very helpful to include detailed setup notes at the top as part of the documentation within the notebook
- What is ptc? I'm guessing photon transfer curve
- How did you know the type of exposure for the different visits (e.g., bias, flat)
- mjds=[(float(visit)*1e-5)+55197 for visit in visits]  # Not sure purpose here?
- Cell 13 throws an error. There's a syntax error in the print statements, but also the data arrays returned seem to be filled with zeros. Note sure what is going on.
- The remainder of cells do not seem to run either. It seems that a dataId is not defined. Difficult to evaluate the rest of the notebook.

**Comment by bstalder** [comment]
Very valid critics.  I will try to add context and descriptions by Friday!

**Comment by bstalder** [comment]
will continue work on this branch

**Pull request closed without merging**
