### PR TITLE
Added example of linked stream with datashader 

### PR DESCRIPTION
**Pull request by afausti**
It shows that we can navigate on a RA, Dec plot using the Bokeh `Wheel zoom` tool and create an histogram for the data within the RA, Dec plot limits. 

- Improved narrative 
- Show first an example of linked stream with `hv.Points()` and `hv.Histogram()` for one patch of data (<~100k data points). 
- Then use datashader to visualize a whole tract (~5M data points)
- Create a new callback function to select data based on the plot x_range, y_range
- Use the the `RangeXY` linked stream to link the datashader plot and the histogram

### CODE REVIEW

**Comment by bechtol** [comment]
This update looks great Angelo. I added an alternative approach to do the selection on a datashaded 2D histogram that uses `BoundsXY` stream instead of the `RangeXY` stream. By using the `BoundsXY`, the user gets to draw a selection box instead of adjusting the zoom, which might be more intuitive. There is also a cell to show how one can use the stream object to grab the selected objects for subsequent analysis.

Sorry if it is not the correct workflow to add another commit onto your pull request.

**Comment by afausti** [comment]
Thanks for the addition Keith! it complements very well the example, the option to grab the selected object for subsequent analysis is generally useful.

**Review by bechtol — APPROVED** [review]
Looks good. Documentation in good shape.

In the future, maybe we would want to create an easy to use utility function for 2D datashader plots with callback

**Comment by womullan** [comment]
In the non data shared version selecting a box changes the histogram, but data shader only changes the histogram if I zoom - even though the code looks correct ..

**Comment by mgckind** [comment]
It's nice that this notebook got extra attention and grew more, it sets a good example to other interactions plots. I'll take a look at @womullan issue

**Comment by afausti** [comment]
@womullan I restarted the kernel, run all cells and it is working for me. On cell 58 output you have the example using `BoundsXY` that let you draw a selection box.  On cell 62 output you have the example using `RangeXY` that updates the histogram when you zoom.  One thing that is confusing though is that on cell 62 output it also shows the `box_select` Bokeh tool and it shouldn't.

**Comment by afausti** [comment]
OK I see`box_select` is shown because both `BoundXY` and `RangeXY` examples are sharing the same instance of `image`. If we create a new instance of `image` right before the `RangeXY` example then `box_select` is not shown. @womullan does that solve your issue?

**Comment by afausti** [comment]
See PR https://github.com/lsst-com/notebooks/pull/30 for my proposed fix.

**Pull request merged**
