### PR TITLE
U/sjs86/color

### PR DESCRIPTION
**Pull request by sschmidt23**
Quick attempt at making color color plots for one tract, mainly just learning about pandas and LSST syntax

### CODE REVIEW

**Comment by mgckind** [comment]
It doesn't load the file on github, I'll add comments from running the notebook directly

**Comment by mgckind** [comment]
- typo 100054 --> 10054
- some cells can be joined in one for easier reading
- there is a long for loop that might need extra comments to understand what's going on

**Comment by mgckind** [comment]
- need to add tables as requirement to write the hdf5

**Comment by mgckind** [comment]
- axes names
- df.concat might not be very efficient, maybe just concatenating numpy arrays and then convert to pandas?

**Review by mgckind — COMMENTED** [review]
- Notebook runs but to write hdf5 needs PyTables
- Extra comments make things easier to understand
- Nice way to get started with catalog data

**Comment by leannep** [comment]
Excellent work - a great example of how to extract data and make colour-colour plots. A few points

- Plots need axes and labels and also titles
- Legends to explain the use of the colours in plots would be helpful

**Review by leannep — APPROVED** [review]
See comments - approve for merge

**Comment by sschmidt23** [comment]
I added some instructions at the beginning on pip installing pandas and pyTables, as well as additional comments throughout the notebook.  I also added missing axis labels and some legends to plots for a bit more clarity.  I will make further changes when I have more time, thanks for the very useful feedback!

**Pull request merged**
